services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - MONGO_URI=mongodb://admin:password@mongodb:27017/nestdb?authSource=admin
        depends_on:
            - mongodb
        networks:
            - app-network

    mongodb:
        image: mongo:7.0
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: nestdb

        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data:
